"use strict";
const userController = require('../controllers/userController');
const express = require("express");
const router = express.Router();
router.get("/", userController.fetchAllUsers);
router.get("/:id", userController.fetchUserById);
router.delete("/:id", userController.removeUser);
router.post("/signup", userController.createUser);
router.post("/login", userController.loginUser);
module.exports = router;